name: mycrypto
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  # Flutter SDK

  # Autenticação
  google_sign_in: ^6.1.5
  firebase_auth: ^4.10.0

  # Banco de dados
  cloud_firestore: ^4.9.0

  # UI/Design
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.1.0
  google_fonts: ^6.0.0

  # Comunicação com APIs
  dio: ^5.3.2

  # Configuração de variáveis de ambiente
  flutter_dotenv: ^5.0.2

  # Renderização de HTML
  flutter_html: ^3.0.0-alpha.5

  # Roteamento e navegação
  flutter_modular: ^5.0.3

  # Personalização de Splash Screen
  flutter_native_splash: ^2.2.4

  # Gerenciamento de estado
  flutter_triple: ^3.0.0

  # Localização e Internacionalização
  flutter_localizations: 
    sdk: flutter
  intl: ^0.17.0

  # Autenticação local
  local_auth: ^2.1.0

  # Animações
  lottie: ^2.6.0
  shimmer: ^3.0.0

  # Gráficos
  syncfusion_flutter_charts: ^23.1.36

  # Navegação por guias
  google_nav_bar: ^5.0.6

  # Alternância de estado
  toggle_switch: ^2.0.1

  # Tradução de texto
  translator_plus: ^1.0.1

  # Deslizar para ação
  flutter_slidable: ^3.0.0

  # Armazenamento de preferências locais
  shared_preferences: ^2.0.17

  # Abertura de URLs externas
  url_launcher: ^6.1.10

  # Texto redimensionável
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.1

  # Anúncios móveis do Google
  google_mobile_ads: ^3.0.0
  rounded_loading_button: ^2.1.0


dependency_overrides:
  firebase_core_platform_interface: 4.7.0
  intl: ^0.18.0

flutter_native_splash:
  color: "#5865F2"
  image: "assets/app/splash.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/app/
    - assets/app/wallet/
    - assets/login/
    - assets/error/
