name: mycrypto
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_html: ^3.0.0-alpha.5
  flutter_modular: ^5.0.3
  flutter_native_splash: ^2.2.4
  flutter_svg: ^1.0.3
  flutter_triple: ^1.2.6
  font_awesome_flutter: ^10.1.0
  google_fonts: ^2.3.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^5.4.0
  intl: ^0.17.0
  local_auth: ^2.1.0
  lottie: ^1.2.2
  rounded_loading_button: ^2.1.0
  shimmer: ^2.0.0
  syncfusion_flutter_charts: ^20.2.40
  toggle_switch: ^2.0.1
  translator: ^0.1.7

flutter_native_splash:
  color: "#5865F2"
  image: "assets/app/splash.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/app/
    - assets/login/
    - assets/error/
