// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlq19tzaqq_qGpKOT10DN9NxDHB0U5LWE',
    appId: '1:124314124257:android:b02be58295136aefcc1ca0',
    messagingSenderId: '124314124257',
    projectId: 'mycrypto-f4fe2',
    storageBucket: 'mycrypto-f4fe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkpZMSy557HaGtupgpdIL8BHFJCSAQ0xg',
    appId: '1:124314124257:ios:e25d443c494c923ccc1ca0',
    messagingSenderId: '124314124257',
    projectId: 'mycrypto-f4fe2',
    storageBucket: 'mycrypto-f4fe2.appspot.com',
    androidClientId: '124314124257-la2lkpscqk9blkc3uqq93rvaujplfigv.apps.googleusercontent.com',
    iosClientId: '124314124257-rtg517hhpq0m022r72n7ioiqv8pioq3e.apps.googleusercontent.com',
    iosBundleId: 'com.app.mycrypto',
  );
}
